In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
# Sentences

sent = ["the glass of milk",
        "the glass of juice",
        "the cup of tea",
        "I am a good boy",
        "I am a good developer",
        "understand the meaning of words",
        "your videos are good",]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# Define the vocabulary size
voc_size = 10000

In [7]:
# One hot representation
one_hot_repr = [one_hot(words, voc_size) for words in sent]

In [8]:
one_hot_repr

[[1257, 7365, 5683, 3898],
 [1257, 7365, 5683, 2584],
 [1257, 5807, 5683, 8936],
 [3595, 1697, 6731, 1001, 2658],
 [3595, 1697, 6731, 1001, 5989],
 [9081, 1257, 9452, 5683, 4975],
 [2957, 5757, 9407, 1001]]

In [9]:
# Word Embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)

In [12]:
embedded_docs

array([[   0,    0,    0,    0, 1257, 7365, 5683, 3898],
       [   0,    0,    0,    0, 1257, 7365, 5683, 2584],
       [   0,    0,    0,    0, 1257, 5807, 5683, 8936],
       [   0,    0,    0, 3595, 1697, 6731, 1001, 2658],
       [   0,    0,    0, 3595, 1697, 6731, 1001, 5989],
       [   0,    0,    0, 9081, 1257, 9452, 5683, 4975],
       [   0,    0,    0,    0, 2957, 5757, 9407, 1001]])

In [13]:
# Feature representation
dim = 10

In [22]:
model = Sequential()
model.add(Embedding(voc_size, dim))
model.compile('adam', 'mse')

In [23]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [24]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step


array([[[ 0.01534227,  0.01928315,  0.03027112,  0.04023274,
          0.04931742,  0.03654352, -0.0072524 , -0.01528465,
         -0.02934669, -0.01095731],
        [ 0.01534227,  0.01928315,  0.03027112,  0.04023274,
          0.04931742,  0.03654352, -0.0072524 , -0.01528465,
         -0.02934669, -0.01095731],
        [ 0.01534227,  0.01928315,  0.03027112,  0.04023274,
          0.04931742,  0.03654352, -0.0072524 , -0.01528465,
         -0.02934669, -0.01095731],
        [ 0.01534227,  0.01928315,  0.03027112,  0.04023274,
          0.04931742,  0.03654352, -0.0072524 , -0.01528465,
         -0.02934669, -0.01095731],
        [ 0.03604967,  0.0346509 ,  0.00409468, -0.04746608,
         -0.01021342,  0.0240539 , -0.00527141, -0.03877728,
         -0.04361491, -0.03887403],
        [-0.02964804,  0.00445155, -0.03444911,  0.01569668,
         -0.03707002,  0.01394871, -0.04920868,  0.03641446,
          0.01633898,  0.04669741],
        [-0.0331523 ,  0.02160779, -0.00559415,  0.0

In [25]:
(embedded_docs[0])

array([   0,    0,    0,    0, 1257, 7365, 5683, 3898])

In [29]:
single_input = np.array(embedded_docs[0]).reshape(1, -1)
model.predict(single_input)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step


array([[[ 0.01534227,  0.01928315,  0.03027112,  0.04023274,
          0.04931742,  0.03654352, -0.0072524 , -0.01528465,
         -0.02934669, -0.01095731],
        [ 0.01534227,  0.01928315,  0.03027112,  0.04023274,
          0.04931742,  0.03654352, -0.0072524 , -0.01528465,
         -0.02934669, -0.01095731],
        [ 0.01534227,  0.01928315,  0.03027112,  0.04023274,
          0.04931742,  0.03654352, -0.0072524 , -0.01528465,
         -0.02934669, -0.01095731],
        [ 0.01534227,  0.01928315,  0.03027112,  0.04023274,
          0.04931742,  0.03654352, -0.0072524 , -0.01528465,
         -0.02934669, -0.01095731],
        [ 0.03604967,  0.0346509 ,  0.00409468, -0.04746608,
         -0.01021342,  0.0240539 , -0.00527141, -0.03877728,
         -0.04361491, -0.03887403],
        [-0.02964804,  0.00445155, -0.03444911,  0.01569668,
         -0.03707002,  0.01394871, -0.04920868,  0.03641446,
          0.01633898,  0.04669741],
        [-0.0331523 ,  0.02160779, -0.00559415,  0.0